services:
  flask_app:
    image: flask_app_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: flaskdb
      DB_USER: root
      DB_PASSWORD: password
    restart: always

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
